services:

  harry_backend:
    build:
      context: ./backend
    container_name: harry_backend
    ports:
      - "8100:8100"
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8100

  harry_frontend:
    build:
      context: ./niceGUI
    container_name: harry_frontend
    ports:
      - "8091:8091"
    restart: always
    command: python3 main.py