services:

  harry_backend:
    build:
      context: ./backend
    container_name: harry_backend
    volumes:
      - ./backend:/backend
    ports:
      - "8090:8090"
    command: python3 /backend/api.py
    restart: always

  harry_frontend:
    build:
      context: ./niceGUI
    container_name: harry_frontend
    volumes:
      - ./niceGUI:/frontend
    ports:
      - "8091:8080"
    command: python3 /frontend/main.py
    restart: always
